// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419212639_comment")]
    partial class comment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AppraisalAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsibleManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("RequestVersionId");

                    b.HasIndex("ResponsibleManagerId");

                    b.HasIndex("UserId");

                    b.HasIndex("DocumentId", "RequestVersionId");

                    b.ToTable("AppraisalAssignments");
                });

            modelBuilder.Entity("Domain.Entities.AppraisalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppraisalAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalAssignmentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("HandlerId");

                    b.HasIndex("RequestVersionId");

                    b.ToTable("AppraisalHistories");
                });

            modelBuilder.Entity("Domain.Entities.AppraisalReviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StaffId");

                    b.ToTable("AppraisalReviewers");
                });

            modelBuilder.Entity("Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppraisalAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCurrentStep")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalAssignmentId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("IsCurrentStep");

                    b.HasIndex("RequestVersionId");

                    b.HasIndex("DocumentId", "StepOrder");

                    b.ToTable("ApprovalWorkflows");
                });

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RequestVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicalDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestVersionId");

                    b.HasIndex("TechnicalDocumentId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Domain.Entities.AttachmentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FeedbackCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FeedbackIssueId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("FeedbackCommentId");

                    b.HasIndex("FeedbackIssueId");

                    b.HasIndex("EntityId", "EntityType");

                    b.HasIndex("EntityId", "EntityType", "AttachmentId")
                        .IsUnique();

                    b.ToTable("AttachmentLinks");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeDepartment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NameDepartment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeDepartment")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Entities.DepartmentInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InviteeEmployeeCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InvitationCode")
                        .IsUnique();

                    b.HasIndex("InviteeEmployeeCode");

                    b.ToTable("DepartmentInvitations");
                });

            modelBuilder.Entity("Domain.Entities.FeedbackComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedbackIssueId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackIssueId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackComments");
                });

            modelBuilder.Entity("Domain.Entities.FeedbackIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppraisalAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppraisalHistoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("IndicatorPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResolvedInVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TechnicalKnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalAssignmentId");

                    b.HasIndex("AppraisalHistoryId");

                    b.HasIndex("AssignedDepartmentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("RequestVersionId");

                    b.HasIndex("ResolvedInVersionId");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicalKnowledgeBaseId");

                    b.HasIndex("DocumentId", "Status");

                    b.ToTable("FeedbackIssues");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Domain.Entities.RequestVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceIssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicalSpecsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceIssueId");

                    b.HasIndex("TechnicalSpecsJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TechnicalSpecsJson"), "gin");

                    b.HasIndex("RequestId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RequestVersions");
                });

            modelBuilder.Entity("Domain.Entities.TechnicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentHandlerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalDepartmentIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentHandlerId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DocumentCode")
                        .IsUnique();

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.ToTable("TechnicalDocuments");
                });

            modelBuilder.Entity("Domain.Entities.TechnicalKnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedSpecPattern")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalSolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LinkedSpecPattern");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LinkedSpecPattern"), "gin");

                    b.HasIndex("Title");

                    b.HasIndex("VerifiedById");

                    b.ToTable("TechnicalKnowledgeBase");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Domain.Entities.AppraisalAssignment", b =>
                {
                    b.HasOne("Domain.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("AppraisalAssignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TechnicalDocument", "Document")
                        .WithMany("AppraisalAssignments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RequestVersion", "Version")
                        .WithMany("AppraisalAssignments")
                        .HasForeignKey("RequestVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "ResponsibleManager")
                        .WithMany()
                        .HasForeignKey("ResponsibleManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("ManagedAssignments")
                        .HasForeignKey("UserId");

                    b.Navigation("AssignedBy");

                    b.Navigation("Department");

                    b.Navigation("Document");

                    b.Navigation("ResponsibleManager");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.AppraisalHistory", b =>
                {
                    b.HasOne("Domain.Entities.AppraisalAssignment", "AppraisalAssignment")
                        .WithMany("AppraisalHistories")
                        .HasForeignKey("AppraisalAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.TechnicalDocument", "Document")
                        .WithMany("AppraisalHistories")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Handler")
                        .WithMany("AppraisalHistories")
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RequestVersion", "RequestVersion")
                        .WithMany("AppraisalHistories")
                        .HasForeignKey("RequestVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppraisalAssignment");

                    b.Navigation("Document");

                    b.Navigation("Handler");

                    b.Navigation("RequestVersion");
                });

            modelBuilder.Entity("Domain.Entities.AppraisalReviewer", b =>
                {
                    b.HasOne("Domain.Entities.AppraisalAssignment", "Assignment")
                        .WithMany("Reviewers")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Staff")
                        .WithMany("AssignedReviews")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.HasOne("Domain.Entities.AppraisalAssignment", "AppraisalAssignment")
                        .WithMany()
                        .HasForeignKey("AppraisalAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.TechnicalDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RequestVersion", "Version")
                        .WithMany()
                        .HasForeignKey("RequestVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppraisalAssignment");

                    b.Navigation("Approver");

                    b.Navigation("Document");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Domain.Entities.RequestVersion", null)
                        .WithMany("Attachments")
                        .HasForeignKey("RequestVersionId");

                    b.HasOne("Domain.Entities.TechnicalDocument", "TechnicalDocument")
                        .WithMany("Attachments")
                        .HasForeignKey("TechnicalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Uploader")
                        .WithMany("UploadedAttachments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TechnicalDocument");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Domain.Entities.AttachmentLink", b =>
                {
                    b.HasOne("Domain.Entities.Attachment", "Attachment")
                        .WithMany("Links")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FeedbackComment", null)
                        .WithMany("AttachmentLinks")
                        .HasForeignKey("FeedbackCommentId");

                    b.HasOne("Domain.Entities.FeedbackIssue", null)
                        .WithMany("AttachmentLinks")
                        .HasForeignKey("FeedbackIssueId");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Parent")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.DepartmentInvitation", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Invitations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Entities.FeedbackComment", b =>
                {
                    b.HasOne("Domain.Entities.FeedbackIssue", "FeedbackIssue")
                        .WithMany("Comments")
                        .HasForeignKey("FeedbackIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FeedbackComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeedbackIssue");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.FeedbackIssue", b =>
                {
                    b.HasOne("Domain.Entities.AppraisalAssignment", null)
                        .WithMany("FeedbackIssues")
                        .HasForeignKey("AppraisalAssignmentId");

                    b.HasOne("Domain.Entities.AppraisalHistory", "AppraisalHistory")
                        .WithMany("FeedbackIssues")
                        .HasForeignKey("AppraisalHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Department", "AssignedDepartment")
                        .WithMany("HandledIssues")
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.TechnicalDocument", "Document")
                        .WithMany("FeedbackIssues")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Reporter")
                        .WithMany("ReportedIssues")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RequestVersion", "Version")
                        .WithMany("IssuesReported")
                        .HasForeignKey("RequestVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RequestVersion", "ResolvedInVersion")
                        .WithMany("IssuesResolved")
                        .HasForeignKey("ResolvedInVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.TechnicalKnowledgeBase", "TechnicalKnowledgeBase")
                        .WithMany()
                        .HasForeignKey("TechnicalKnowledgeBaseId");

                    b.Navigation("AppraisalHistory");

                    b.Navigation("AssignedDepartment");

                    b.Navigation("Document");

                    b.Navigation("Reporter");

                    b.Navigation("ResolvedInVersion");

                    b.Navigation("TechnicalKnowledgeBase");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entities.Profile", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RequestVersion", b =>
                {
                    b.HasOne("Domain.Entities.TechnicalDocument", "Request")
                        .WithMany("Versions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FeedbackIssue", "OriginatingIssue")
                        .WithMany()
                        .HasForeignKey("SourceIssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OriginatingIssue");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Domain.Entities.TechnicalDocument", b =>
                {
                    b.HasOne("Domain.Entities.User", "CurrentHandler")
                        .WithMany("HandlingDocuments")
                        .HasForeignKey("CurrentHandlerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Documents")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Requester")
                        .WithMany("RequestedDocuments")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentHandler");

                    b.Navigation("Department");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Domain.Entities.TechnicalKnowledgeBase", b =>
                {
                    b.HasOne("Domain.Entities.User", "Verifier")
                        .WithMany("VerifiedKnowledgeBases")
                        .HasForeignKey("VerifiedById");

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("Domain.Entities.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AppraisalAssignment", b =>
                {
                    b.Navigation("AppraisalHistories");

                    b.Navigation("FeedbackIssues");

                    b.Navigation("Reviewers");
                });

            modelBuilder.Entity("Domain.Entities.AppraisalHistory", b =>
                {
                    b.Navigation("FeedbackIssues");
                });

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("AppraisalAssignments");

                    b.Navigation("Documents");

                    b.Navigation("HandledIssues");

                    b.Navigation("Invitations");

                    b.Navigation("SubDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.FeedbackComment", b =>
                {
                    b.Navigation("AttachmentLinks");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Domain.Entities.FeedbackIssue", b =>
                {
                    b.Navigation("AttachmentLinks");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("Domain.Entities.RequestVersion", b =>
                {
                    b.Navigation("AppraisalAssignments");

                    b.Navigation("AppraisalHistories");

                    b.Navigation("Attachments");

                    b.Navigation("IssuesReported");

                    b.Navigation("IssuesResolved");
                });

            modelBuilder.Entity("Domain.Entities.TechnicalDocument", b =>
                {
                    b.Navigation("AppraisalAssignments");

                    b.Navigation("AppraisalHistories");

                    b.Navigation("Attachments");

                    b.Navigation("FeedbackIssues");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AppraisalHistories");

                    b.Navigation("AssignedReviews");

                    b.Navigation("Comments");

                    b.Navigation("HandlingDocuments");

                    b.Navigation("ManagedAssignments");

                    b.Navigation("Profile");

                    b.Navigation("ReportedIssues");

                    b.Navigation("RequestedDocuments");

                    b.Navigation("UploadedAttachments");

                    b.Navigation("UserNotifications");

                    b.Navigation("VerifiedKnowledgeBases");
                });
#pragma warning restore 612, 618
        }
    }
}
